# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alanintegrations.com
title: Alan Integrations
email: info@alanintegrations.com
author: Rob Snyder
description: Alan Integrations website. Bringing People and Technology Together
copyright: 'Copyright &copy; 2016 Alan Integrations. All Rights Reserved.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    icon: envelope
    url: mailto:info@alanintegrations.com
#  - title: twitter
#    icon: twitter
#    url: https://twitter.com/ssnnyyddeerr
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/company/alan-integrations
  - title: github
    icon: github
    url: https://github.com/alanintegrations
  
